# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 18:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DJHueyAcksLate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('status', models.CharField(choices=[('_QUEUED_', 'Queued'), ('_IN_PROGRESS_', 'In Progress'), ('_DONE_', 'Done')], default='_IN_PROGRESS_', max_length=32, verbose_name='Status of the report')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
